# Generated by Django 3.2.8 on 2021-10-31 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_list', '0004_rename_book_author_book_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='writer',
            new_name='author',
        ),
    ]
