# Generated by Django 3.2.8 on 2021-10-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_list', '0005_rename_writer_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
