# Generated by Django 3.2.8 on 2021-10-31 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_list', '0007_auto_20211031_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='status',
            new_name='completed',
        ),
    ]
