# Generated by Django 3.2.8 on 2021-10-31 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_list', '0008_rename_status_book_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='book_author',
        ),
    ]
