# Generated by Django 3.2.8 on 2021-11-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_list', '0009_rename_author_book_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='completed',
            field=models.BooleanField(),
        ),
    ]
