# Generated by Django 3.2.8 on 2021-11-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_list', '0011_alter_book_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
